version: '3.8'

services:
  postgres:
    container_name: postgres
    image: 'postgres:14'
    restart: 'unless-stopped'
    environment:
      PGDATA: '/var/lib/postgresql/data/pgdata'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'pet4lov'
    ports:
      - '5432:5432'