# Generated by Django 4.1.1 on 2022-09-05 22:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id_animal', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('breed', models.CharField(max_length=50)),
                ('birth_date', models.IntegerField()),
                ('adoption_date', models.DateTimeField(auto_now_add=True)),
                ('health_condition', models.CharField(max_length=200)),
            ],
        ),
    ]
