# Generated by Django 5.0.2 on 2024-02-23 14:15

import adocao.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ONG',
            fields=[
                ('id_ong', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=100)),
                ('endereco', models.TextField()),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_cpf', models.BigIntegerField(blank=True, null=True)),
                ('birth_date', models.DateField()),
                ('adress', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id_animal', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=50)),
                ('name_animal', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(max_length=20)),
                ('breed', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('adoption_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('health_condition', models.CharField(max_length=200)),
                ('vacine_status', models.CharField(blank=True, max_length=50, null=True)),
                ('vermifugue_status', models.CharField(blank=True, max_length=50, null=True)),
                ('observations', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=adocao.models.upload_image_animal)),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adocao.ong')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioAdotante',
            fields=[
                ('id_user', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_cpf', models.BigIntegerField(blank=True, null=True)),
                ('birth_date', models.DateField()),
                ('adress', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('animal_adotado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adocao.pet')),
            ],
        ),
    ]
