# Generated by Django 5.0.2 on 2024-02-23 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ong',
            old_name='endereco',
            new_name='adress',
        ),
        migrations.RenameField(
            model_name='ong',
            old_name='cidade',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='ong',
            old_name='estado',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ong',
            old_name='nome',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='ong',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='ong',
            name='resposable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adocao.usuarioadmin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarioadmin',
            name='name',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
