# Generated by Django 5.0.2 on 2024-03-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0003_alter_usuario_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='adoption_date',
            field=models.DateTimeField(null=True),
        ),
    ]
