# Generated by Django 5.0.2 on 2024-03-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0004_alter_pet_adoption_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='adoption_date',
            field=models.CharField(null=True),
        ),
    ]
