# Generated by Django 5.0.2 on 2024-03-15 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0005_alter_pet_adoption_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='responsable_pet',
            field=models.ForeignKey(default=11111, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
