# Generated by Django 4.1.1 on 2022-09-07 21:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_animals_observations_animals_vacine_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adocao',
            fields=[
                ('id_adocao', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_doacao', models.UUIDField(editable=False)),
                ('id_user', models.UUIDField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id_doacao', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_user', models.UUIDField(editable=False)),
                ('id_animal', models.UUIDField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('document_cpf', models.BigIntegerField(blank=True, null=True)),
                ('birth_date', models.DateField()),
                ('adress', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
